services:
  # Infrastructure: MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - biblio-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Infrastructure: Kafka & Zookeeper
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - biblio-network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - biblio-network

  # Microservices
  eureka-server:
    build: ./eurika
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - biblio-network

  gateway-service:
    build: ./gateway
    container_name: gateway-service
    ports:
      - "9999:9999"
    environment:
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
    networks:
      - biblio-network

  user-service:
    build: ./user
    container_name: user-service
    environment:
      - EUREKA_HOST=eureka-server
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - eureka-server
      - mysql
    networks:
      - biblio-network

  book-service:
    build: ./book
    container_name: book-service
    environment:
      - EUREKA_HOST=eureka-server
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - eureka-server
      - mysql
    networks:
      - biblio-network

  emprunt-service:
    build: ./emprunter
    container_name: emprunt-service
    environment:
      - EUREKA_HOST=eureka-server
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - KAFKA_HOST=kafka
    depends_on:
      - eureka-server
      - mysql
      - kafka
      - user-service
      - book-service
    networks:
      - biblio-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      - EUREKA_HOST=eureka-server
      - KAFKA_HOST=kafka
    depends_on:
      - eureka-server
      - kafka
    networks:
      - biblio-network

networks:
  biblio-network:
    driver: bridge
